import "./globals.css";

import { AuthProvider } from "@/context/AuthContext";
import { FeedbackProvider } from "@/context/FeedbackContext";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { SidebarProvider } from "@/context/SidebarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FeedbackProvider>
          <SidebarProvider>
            <AuthProvider>{children}</AuthProvider>
          </SidebarProvider>
        </FeedbackProvider>
      </body>
    </html>
  );
}
