import "./globals.css";

import { DM_Sans } from "next/font/google";
import { FeedbackProvider } from "@/context/FeedbackContext";
import type { Metadata } from "next";

const sans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <FeedbackProvider>{children}</FeedbackProvider>
      </body>
    </html>
  );
}
